

### Login
POST {{baseUrl}}/login
Authorization: Basic {{appUsername}} {{appUserPassword}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body.token !== null, "Redirect URL is empty");
        client.global.set("jwtToken", response.body.token)
    });
%}


### Create new Journey
POST http://localhost:8080/rest/journey
Authorization: Basic {{USER_NAME}} {{PASSWORD}}
Content-Type: application/json

{
  "name" : "First Flight Experience",
  "title" : "One of the most beautiful experience ever in my life",
  "description" : "Travelled first time for work deputation to Germany, Munich city",
  "category" : "Travel",
  "city" : "Munich",
  "country" : "Germany",
  "tags" : ["Travel", "Germany", "Munich"],
  "thumbnail" : "valid image id",
  "location" : {
    "type": "Point",
    "coordinates": [100.0, 0.0]
  },
  "journeyDate": "2021-08-04"
}

### Find all Journeys
GET {{baseUrl}}/journeys
Authorization: Bearer {{jwtToken}}
Accept: application/json


### Find Journey
GET {{baseUrl}}/journey/66042f634acf0200fb6db1e9
Authorization: Basic {{appUsername}} {{appUserPassword}}
Accept: application/json


### Find all Journeys and return Geo Json
GET {{baseUrl}}/public/journeys
Authorization: Basic {{appUsername}} {{appUserPassword}}
Accept: application/geo+json

