### Create new Journey
POST http://localhost:8080/rest/journey
Content-Type: application/json

{
  "name" : "First Flight Experience",
  "title" : "One of the most beautiful experience ever in my life",
  "description" : "Travelled first time for work deputation to Germany, Munich city",
  "category" : "Travel",
  "city" : "Munich",
  "country" : "Germany",
  "tags" : ["Travel", "Germany", "Munich"],
  "thumbnail" : "valid image id",
  "location" : {
    "type": "Point",
    "coordinates": [100.0, 0.0]
  },
  "journeyDate": "2024-03-27"
}


### Find Journey
GET http://localhost:8080/rest/journey/6603d70deb26b82f8448c556
Accept: application/json