
### Login as Application user
POST {{baseUrl}}/login
Authorization: Basic {{appUsername}} {{appUserPassword}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body.token !== null, "Redirect URL is empty");
        client.global.set("jwtToken", response.body.token)
    });
%}

### Send Email Code
POST {{baseUrl}}/sendEmailCode
Authorization: Bearer {{jwtToken}}

### Verify Email Code
POST {{baseUrl}}/verifyEmailCode
Authorization: Bearer {{jwtToken}}
Content-Type: application/json

{
  "code": "202872"
}