version: "3.8"
services:
  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
      - "127.0.0.1:1025:1025"
      - "127.0.0.1:8025:8025"
  mongodb:
    image: mongo
    container_name: mongo
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongodb_user
      - MONGO_INITDB_ROOT_PASSWORD=mongodb_pwd

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "127.0.0.1:9090:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongodb_user
      - ME_CONFIG_MONGODB_ADMINPASSWORD=mongodb_pwd
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_AUTH_USERNAME=admin
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=pass

volumes:
  data: {}

networks:
  default:
    name: mongodb_network

