app:
  ui-app-url: http://localhost:4200
  operational:
    users:
      - username: GUEST
        password: <placeholder>
        roles: GUEST_USER
        name: Guest
  security:
    cors:
      properties:
        - path: /**
          allowed-origins: http://localhost:4200, https://nramc.github.io
          allowed-methods: GET, POST, PUT, DELETE
          allowed-headers:
            - Authorization
            - Content-Type
          allow-credentials: true


logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.data.mongodb.core: DEBUG
#    org.springframework.boot.autoconfigure: DEBUG

jwt:
  private-key: classpath:app.key
  public-key: classpath:app.pub
  ttl: 1h
  issuer: self

spring:
  mail:
    username: noreply@journey.com
    password: test-password
    host: localhost
    port: 1025
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false
      mail.smtp.starttls.required: false
