app:
  operational:
    users:
      - name: localDevAdmin
        username: admin
        password: password
        roles: USER, MAINTAINER, ADMINISTRATOR
      - username: GUEST
        password: <placeholder>
        roles: GUEST
        name: Guest
      - username: test-user-001
        password: test-password-001
        roles: AUTHENTICATED_USER, MAINTAINER
        name: Test User 001

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.data.mongodb.core: DEBUG
#    org.springframework.boot.autoconfigure: DEBUG

jwt:
  private-key: classpath:app.key
  public-key: classpath:app.pub
  ttl: 1h
  issuer: self
