spring:
  application:
    name: ${app.name}
  data:
    mongodb:
      database: journey-dev
      auto-index-creation: true

app:
  name: Journey API
  version: '@project.version@'
  user:
    username: ${OPR_USER}
    password: ${OPR_USER_PWD}
    roles: ${OPR_USER_ROLES}



