spring:
  application:
    name: ${app.name}
  data:
    mongodb:
      database: journey-dev
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${NOREPLY_EMAIL}
    password: ${NOREPLY_EMAIL_PWD}
    test-connection: true
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true

app:
  name: Journey API
  version: '@project.version@'
  operational:
    users:
      - username: ${OPR_USER}
        password: ${OPR_USER_PWD}
        roles: ${OPR_USER_ROLES}
        name: Administrator
      - username: GUEST
        password: <placeholder>
        roles: GUEST_USER
        name: Guest
  security:
    cors:
      properties:
        - path: /**
          allowed-origins: https://nramc.github.io
          allowed-methods: GET, POST, PUT, OPTIONS, DELETE
          allowed-headers:
            - Authorization
            - Content-Type
          allow-credentials: true


jwt:
  private-key: 'file:/etc/secrets/jwt-private.key'
  public-key: 'file:/etc/secrets/jwt-public.pub'
  ttl: 1h
  issuer: self

springdoc:
  api-docs:
    enabled: true
    path: /doc/openapi

  swagger-ui:
    queryConfigEnabled: true
    path: /doc/swagger-ui.html
  group-configs:
    - group: Journeys
      packages-to-scan:
        - com.github.nramc.dev.journey.api.web.resources.rest.journeys
    - group: Users
      packages-to-scan:
        - com.github.nramc.dev.journey.api.web.resources.rest.users
    - group: Auth
      packages-to-scan:
        - com.github.nramc.dev.journey.api.web.resources.rest.auth
    - group: API Info
      packages-to-scan:
        - com.github.nramc.dev.journey.api.web.resources.rest.api

service:
  cloudinary:
    api-key: ${CLOUDINARY_API_KEY}
    api-secret: ${CLOUDINARY_API_SECRET}
    cloud-name: ${CLOUDINARY_CLOUD_NAME}
    additional-properties:
      secure: true

