spring:
  application:
    name: ${app.name}
  data:
    mongodb:
      database: journey-dev
      auto-index-creation: true
  mail:
    host:
    port:
    username: ${NOREPLY_EMAIL}
    password: ${NOREPLY_EMAIL_PWD}
    test-connection: true
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true

app:
  name: Journey API
  version: '@project.version@'
  ui-app-url: https://nramc.github.io/journeys
  security:
    totp:
      number-of-digits: 6
      secret-length: 32
      totp-algorithm: SHA1
      time-step-size-in-seconds: 30
      max-allowed-time-step-discrepancy: 1
      qr-type: totp
      qr-width: 500
      qr-height: 500
      qr-issuer: Journey
    cors:
      properties:
        - path: /**
          allowed-origins: https://nramc.github.io
          allowed-methods: GET, POST, PUT, OPTIONS, DELETE
          allowed-headers:
            - Authorization
            - Content-Type
            - X-Async-Process
          allow-credentials: true


jwt:
  private-key: 'file:/etc/secrets/jwt-private.key'
  public-key: 'file:/etc/secrets/jwt-public.pub'
  ttl: 1h
  issuer: self

springdoc:
  api-docs:
    enabled: true
    path: /doc/openapi

  swagger-ui:
    queryConfigEnabled: true
    path: /doc/swagger-ui.html
  group-configs:
    - group: Journeys
      packages-to-scan:
        - com.github.nramc.dev.journey.api.web.resources.rest.journeys
    - group: Users
      packages-to-scan:
        - com.github.nramc.dev.journey.api.web.resources.rest.users
    - group: Auth
      packages-to-scan:
        - com.github.nramc.dev.journey.api.web.resources.rest.auth
    - group: API Info
      packages-to-scan:
        - com.github.nramc.dev.journey.api.web.resources.rest.api
    - group: Timeline
      packages-to-scan:
        - com.github.nramc.dev.journey.api.web.resources.rest.timeline

service:
  cloudinary:
    api-key: ${CLOUDINARY_API_KEY}
    api-secret: ${CLOUDINARY_API_SECRET}
    cloud-name: ${CLOUDINARY_CLOUD_NAME}
    additional-properties:
      secure: true
    root-directory: journey/journey-dev

