env:
  contexts:
  - name: journey-api
    urls:
    - http://localhost:8080
    includePaths:
    - http://localhost:8080.*
    authentication:
      method: json
      parameters:
        loginPageUrl: http://localhost:8080/rest/guestLogin
        loginRequestUrl: http://localhost:8080/rest/guestLogin
        loginRequestBody: "{\"username\":\"{%username%}\",\"password\":\"{%password%}\"\
          }"
      verification:
        method: response
        pollFrequency: 60
        pollUnits: requests
        pollUrl: ""
        pollPostData: ""
    sessionManagement:
      method: headers
      parameters:
        Authorization: "Bearer {%json:token%}"
    technology: {}
    structure: {}
    users:
    - name: journey-user
      credentials:
        username: ${APP_USERNAME}
        password: ${APP_PASSWORD}
  parameters: {}
  vars:
    APP_USERNAME: "Journey-Test@123"
    APP_PASSWORD: "journey-test-user@journey.com"
jobs:
- type: passiveScan-config
  parameters: {}
- type: openapi
  parameters:
    apiUrl: http://localhost:8080/doc/openapi
    targetUrl: http://localhost:8080
    context: journey-api
    user: journey-user
- type: passiveScan-wait
  parameters: {}
- type: activeScan
  parameters: {}
  policyDefinition: {}
- type: exitStatus
  parameters: {}

