env:
  contexts:
  - name: journey-api
    urls:
    - http://journey-ci:8080
    includePaths:
    - http://journey-ci:8080.*
    authentication:
      method: json
      parameters:
        loginPageUrl: http://journey-ci:8080/rest/guestLogin
        loginRequestUrl: http://journey-ci:8080/rest/guestLogin
        loginRequestBody: "{\"username\":\"{%username%}\",\"password\":\"{%password%}\"\
          }"
      verification:
        method: response
        pollFrequency: 60
        pollUnits: requests
        pollUrl: ""
        pollPostData: ""
    sessionManagement:
      method: headers
      parameters:
        Authorization: "Bearer {%json:token%}"
    technology: {}
    structure: {}
    users:
    - name: journey-user
      credentials:
        password: Journey-Test@123
        username: journey-test-user@journey.com
  parameters: {}
jobs:
- type: passiveScan-config
  parameters: {}
- type: openapi
  parameters:
    apiUrl: http://journey-ci:8080/doc/openapi
    targetUrl: http://journey-ci:8080
    context: journey-api
    user: journey-user
- type: passiveScan-wait
  parameters: {}
- type: activeScan
  parameters: {}
  policyDefinition: {}
- type: report
  parameters:
    reportTitle: ZAP by Checkmarx Scanning Report
- type: exitStatus
  parameters: {}

