env:
  contexts:
  - name: journey-api
    urls:
    - ${JOURNEY_BASE_URL}
    includePaths:
    - ${JOURNEY_BASE_URL}.*
    authentication:
      method: json
      parameters:
        loginPageUrl: ${JOURNEY_BASE_URL}/rest/guestLogin
        loginRequestUrl: ${JOURNEY_BASE_URL}/rest/guestLogin
        loginRequestBody: "{\"username\":\"{%username%}\",\"password\":\"{%password%}\"\
          }"
      verification:
        method: response
        pollFrequency: 60
        pollUnits: requests
        pollUrl: ""
        pollPostData: ""
    sessionManagement:
      method: headers
      parameters:
        Authorization: "Bearer {%json:token%}"
    technology: {}
    structure: {}
    users:
    - name: journey-user
      credentials:
        password: ${JOURNEY_PASSWORD}
        username: ${JOURNEY_USERNAME}
  parameters: {}
jobs:
- type: passiveScan-config
  parameters: {}
- type: openapi
  parameters:
    apiUrl: ${JOURNEY_BASE_URL}/doc/openapi
    targetUrl: ${JOURNEY_BASE_URL}
    context: journey-api
    user: journey-user
- type: passiveScan-wait
  parameters: {}
- type: activeScan
  parameters: {}
  policyDefinition: {}
- type: report
  parameters:
    reportTitle: ZAP by Checkmarx Scanning Report
- type: exitStatus
  parameters: {}

