@baseUrl=http://localhost:8080

### Login as Guest user
POST {{baseUrl}}/rest/guestLogin


> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body.token !== null, "Redirect URL is empty");
        client.global.set("jwtToken", response.body.token)
    });
%}


### Find all Journeys
GET {{baseUrl}}/journeys
Authorization: Bearer {{jwtToken}}
Accept: application/json


### Find Journey By ID
GET {{baseUrl}}/journey/journey-123
Authorization: Bearer {{jwtToken}}
Accept: application/json


### Find all Journeys and return Geo Json
GET {{baseUrl}}/journeys/published
Authorization: Bearer {{jwtToken}}
Accept: application/geo+json
