

### Login
POST {{baseUrl}}/login
Authorization: Basic {{adminUsername}} {{adminUserPassword}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body.token !== null, "Redirect URL is empty");
        client.global.set("jwtToken", response.body.token)
    });
%}


### Create new Journey
POST http://localhost:8080/rest/journey
Authorization: Bearer {{jwtToken}}
Content-Type: application/json

{
  "name" : "Creating Journey with http client script",
  "title" : "One of the most beautiful experience ever in my life",
  "description" : "Travelled first time for work deputation to Germany, Munich city",
  "category" : "Travel",
  "city" : "Munich",
  "country" : "Germany",
  "tags" : ["travel", "germany", "munich", "dev", "http-client"],
  "thumbnail" : "https://res.cloudinary.com/journeytogether/image/upload/v1712604194/journey/readonly/aeqhy3zwrwko7ba2rinr.jpg",
  "icon": "default",
  "location" : {
    "type": "Point",
    "coordinates": [{{$random.float(-180, 180)}}, {{$random.float(-90, 90)}}]
  },
  "journeyDate": "2021-08-04"
}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 201, "Response status is not 201");
        client.assert(response.body.id !== null, "ID is empty");
        client.global.set("journeyId", response.body.id)
    });
%}

### Find all Journeys
GET {{baseUrl}}/journeys
Authorization: Bearer {{jwtToken}}
Accept: application/json


### Find Journey By ID
GET {{baseUrl}}/journey/{{journeyId}}
Authorization: Bearer {{jwtToken}}
Accept: application/json


### Find all Journeys and return Geo Json
GET {{baseUrl}}/journeys/published
Authorization: Bearer {{jwtToken}}
Accept: application/geo+json

