

### Login as Adminstrator
POST {{baseUrl}}/login
Authorization: Basic {{adminUsername}} {{adminUserPassword}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body.token !== null, "Redirect URL is empty");
        client.global.set("jwtToken", response.body.token)
    });
%}

### Find all users
GET {{baseUrl}}/users
Authorization: Bearer {{jwtToken}}

### Delete user account
DELETE {{baseUrl}}/user/app-user001
Authorization: Bearer {{jwtToken}}

